USE DataMart_SisBanca
GO

CREATE TABLE DIM_EMPLEADO
(
ID_DIM_EMPLEADO INT IDENTITY(1,1) PRIMARY KEY,
ID_EM INT,
NOMBRE_EM VARCHAR(250),
APE_PATE VARCHAR(250),
APE_MATE VARCHAR(250),
SUCURSAL VARCHAR(250),
CARGO VARCHAR(250),
SUELDO FLOAT
)
GO

ALTER TABLE HECHOS ADD ID_DIM_EMPLEADO INT
GO

ALTER TABLE HECHOS ADD CONSTRAINT FK_DIM_EMP_HECHOS FOREIGN KEY(ID_DIM_EMPLEADO) REFERENCES DIM_EMPLEADO(ID_DIM_EMPLEADO)
GO

--POBLANDO DIM EMPLEADOS  (APLICARLO AL INTEGRARION SERVICE YN PASO MAS ANTES DE  LLENAR LA TABLA HECHOS)
INSERT INTO DIM_EMPLEADO (ID_EM,NOMBRE_EM,APE_PATE,APE_MATE,SUCURSAL,CARGO,SUELDO) 
SELECT E.ID_EM,E.NOM_EMPLEADO, E.APE_PATE, E.APE_MATE, S.DIRECCION,CE.NOM_CARGO,E.SUELDO FROM SISTEMA_BANCARIO.DBO.EMPLEADO E 
INNER JOIN SISTEMA_BANCARIO.DBO.SUCURSAL S ON E.ID_SUCURSAL = S.ID_SUCURSAL
INNER JOIN SISTEMA_BANCARIO.DBO.CARGO_EMPLEADO CE ON CE.ID_CARGO_EM = E.ID_CARGO_EM
GO